use_frameworks!

platform :ios, '10.0'

target 'iOS_Hosted_plugin_Example' do
  pod 'iOS_Hosted_plugin', :path => '../'

  target 'iOS_Hosted_plugin_Tests' do
    inherit! :search_paths

    
  end
end
